import type { BriefingCategory } from "./types";

const RSSHUB_BASE_URL = (process.env.RSSHUB_BASE_URL || "https://rsshub.app").replace(/\/$/, "");

export interface PresetNewsSource {
  kind: "rss";
  name: string;
  url: string;
  category: BriefingCategory;
  region: "cn" | "global" | "us";
  weight: number;
  enabled?: boolean;
}

export const PRESET_NEWS_SOURCES: PresetNewsSource[] = [
  {
    kind: "rss",
    name: "英国广播公司中文网",
    url: "https://feeds.bbci.co.uk/zhongwen/simp/rss.xml",
    category: "world",
    region: "global",
    weight: 80,
  },
  {
    kind: "rss",
    name: "中国新闻网国际",
    url: "https://www.chinanews.com.cn/rss/world.xml",
    category: "world",
    region: "cn",
    weight: 76,
  },
  {
    kind: "rss",
    name: "中国新闻网财经",
    url: "https://www.chinanews.com.cn/rss/finance.xml",
    category: "finance",
    region: "cn",
    weight: 74,
  },
  {
    kind: "rss",
    name: "联合国新闻中文",
    url: "https://news.un.org/feed/subscribe/zh/news/all/rss.xml",
    category: "world",
    region: "global",
    weight: 78,
  },
  {
    kind: "rss",
    name: "联合国新闻全球",
    url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
    category: "world",
    region: "global",
    weight: 60,
  },
  {
    kind: "rss",
    name: "CBS 世界",
    url: "https://www.cbsnews.com/latest/rss/world",
    category: "world",
    region: "us",
    weight: 58,
  },
  {
    kind: "rss",
    name: "ABC 国际",
    url: "https://abcnews.go.com/abcnews/internationalheadlines",
    category: "world",
    region: "us",
    weight: 56,
  },
  {
    kind: "rss",
    name: "纽约时报中文网",
    url: "https://cn.nytimes.com/rss/",
    category: "world",
    region: "global",
    weight: 70,
  },
  {
    kind: "rss",
    name: "CNBC 全球市场",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    category: "finance",
    region: "us",
    weight: 66,
  },
  {
    kind: "rss",
    name: "CNBC 投资市场",
    url: "https://www.cnbc.com/id/15839069/device/rss/rss.html",
    category: "finance",
    region: "us",
    weight: 64,
  },
  {
    kind: "rss",
    name: "MarketWatch",
    url: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    category: "finance",
    region: "us",
    weight: 60,
  },
  {
    kind: "rss",
    name: "Seeking Alpha 快讯",
    url: "https://seekingalpha.com/market_currents.xml",
    category: "finance",
    region: "us",
    weight: 55,
  },
  {
    kind: "rss",
    name: "36氪",
    url: "https://36kr.com/feed",
    category: "ai_tech",
    region: "cn",
    weight: 65,
  },
  {
    kind: "rss",
    name: "极客公园",
    url: "https://www.geekpark.net/rss",
    category: "ai_tech",
    region: "cn",
    weight: 75,
  },
  {
    kind: "rss",
    name: "InfoQ 中文",
    url: "https://www.infoq.cn/feed",
    category: "ai_tech",
    region: "cn",
    weight: 72,
  },
  {
    kind: "rss",
    name: "少数派",
    url: "https://sspai.com/feed",
    category: "ai_tech",
    region: "cn",
    weight: 58,
  },
  {
    kind: "rss",
    name: "V2EX 热门",
    url: "https://www.v2ex.com/feed/tab/hot.xml",
    category: "ai_tech",
    region: "cn",
    weight: 52,
  },
  {
    kind: "rss",
    name: "LinuxDo 最新",
    url: "https://linux.do/latest.rss",
    category: "ai_tech",
    region: "cn",
    weight: 50,
  },
  {
    kind: "rss",
    name: "微博热搜",
    url: `${RSSHUB_BASE_URL}/weibo/search/hot`,
    category: "world",
    region: "cn",
    weight: 42,
  },
  {
    kind: "rss",
    name: "知乎热榜",
    url: `${RSSHUB_BASE_URL}/zhihu/hot`,
    category: "world",
    region: "cn",
    weight: 44,
  },
  {
    kind: "rss",
    name: "B站排行榜",
    url: `${RSSHUB_BASE_URL}/bilibili/ranking/0/3/1`,
    category: "ai_tech",
    region: "cn",
    weight: 38,
  },
  {
    kind: "rss",
    name: "掘金热榜",
    url: `${RSSHUB_BASE_URL}/juejin/trending/all/weekly`,
    category: "ai_tech",
    region: "cn",
    weight: 46,
  },
  {
    kind: "rss",
    name: "GitHub Trending",
    url: `${RSSHUB_BASE_URL}/github/trending/daily`,
    category: "ai_tech",
    region: "global",
    weight: 54,
  },
  {
    kind: "rss",
    name: "IT之家",
    url: "https://www.ithome.com/rss/",
    category: "ai_tech",
    region: "cn",
    weight: 74,
  },
  {
    kind: "rss",
    name: "爱范儿",
    url: "https://www.ifanr.com/feed",
    category: "ai_tech",
    region: "cn",
    weight: 70,
  },
  {
    kind: "rss",
    name: "钛媒体",
    url: "https://www.tmtpost.com/rss.xml",
    category: "ai_tech",
    region: "cn",
    weight: 68,
  },
  {
    kind: "rss",
    name: "量子位",
    url: "https://www.qbitai.com/feed",
    category: "ai_tech",
    region: "cn",
    weight: 68,
  },
  {
    kind: "rss",
    name: "Solidot",
    url: "https://www.solidot.org/index.rss",
    category: "ai_tech",
    region: "cn",
    weight: 60,
  },
  {
    kind: "rss",
    name: "TechCrunch AI",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    category: "ai_tech",
    region: "us",
    weight: 70,
  },
  {
    kind: "rss",
    name: "The Verge AI",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    category: "ai_tech",
    region: "us",
    weight: 70,
  },
  {
    kind: "rss",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    category: "ai_tech",
    region: "us",
    weight: 60,
  },
  {
    kind: "rss",
    name: "Ars Technica",
    url: "https://feeds.arstechnica.com/arstechnica/index/",
    category: "ai_tech",
    region: "us",
    weight: 60,
  },
  {
    kind: "rss",
    name: "WIRED",
    url: "https://www.wired.com/feed/rss",
    category: "ai_tech",
    region: "us",
    weight: 58,
  },
  {
    kind: "rss",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    category: "ai_tech",
    region: "us",
    weight: 58,
  },
  {
    kind: "rss",
    name: "Engadget",
    url: "https://www.engadget.com/rss.xml",
    category: "ai_tech",
    region: "us",
    weight: 54,
  },
  {
    kind: "rss",
    name: "IEEE Spectrum",
    url: "https://spectrum.ieee.org/feed",
    category: "ai_tech",
    region: "us",
    weight: 56,
  },
  {
    kind: "rss",
    name: "OpenAI Blog",
    url: "https://openai.com/blog/rss.xml",
    category: "ai_tech",
    region: "us",
    weight: 82,
  },
  {
    kind: "rss",
    name: "Google DeepMind",
    url: "https://deepmind.google/blog/rss.xml",
    category: "ai_tech",
    region: "us",
    weight: 80,
  },
  {
    kind: "rss",
    name: "Google Research",
    url: "https://research.google/blog/rss/",
    category: "ai_tech",
    region: "us",
    weight: 74,
  },
  {
    kind: "rss",
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    category: "ai_tech",
    region: "global",
    weight: 70,
  },
  {
    kind: "rss",
    name: "arXiv 机器学习",
    url: "https://rss.arxiv.org/rss/cs.LG",
    category: "ai_tech",
    region: "global",
    weight: 55,
  },
  {
    kind: "rss",
    name: "arXiv AI 论文",
    url: "https://rss.arxiv.org/rss/cs.AI",
    category: "ai_tech",
    region: "global",
    weight: 55,
  },
  {
    kind: "rss",
    name: "Simon Willison",
    url: "https://simonwillison.net/atom/everything/",
    category: "ai_tech",
    region: "global",
    weight: 66,
  },
  {
    kind: "rss",
    name: "Ben's Bites",
    url: "https://bensbites.beehiiv.com/feed",
    category: "ai_tech",
    region: "global",
    weight: 62,
  },
  {
    kind: "rss",
    name: "TLDR AI",
    url: "https://tldr.tech/api/rss/ai",
    category: "ai_tech",
    region: "global",
    weight: 62,
  },
  {
    kind: "rss",
    name: "Import AI",
    url: "https://importai.substack.com/feed",
    category: "ai_tech",
    region: "global",
    weight: 60,
  },
  {
    kind: "rss",
    name: "MarkTechPost",
    url: "https://marktechpost.com/feed/",
    category: "ai_tech",
    region: "global",
    weight: 54,
  },
  {
    kind: "rss",
    name: "Hacker News",
    url: "https://hnrss.org/frontpage",
    category: "ai_tech",
    region: "global",
    weight: 56,
  },
  {
    kind: "rss",
    name: "Hacker News ≥100分",
    url: "https://hnrss.org/frontpage?points=100",
    category: "ai_tech",
    region: "global",
    weight: 64,
  },
  {
    kind: "rss",
    name: "ByteByteGo",
    url: "https://blog.bytebytego.com/feed",
    category: "ai_tech",
    region: "global",
    weight: 62,
  },
  {
    kind: "rss",
    name: "The Pragmatic Engineer",
    url: "https://newsletter.pragmaticengineer.com/feed",
    category: "ai_tech",
    region: "global",
    weight: 62,
  },
  {
    kind: "rss",
    name: "GitHub Blog",
    url: "https://github.blog/feed/",
    category: "ai_tech",
    region: "global",
    weight: 58,
  },
  {
    kind: "rss",
    name: "Cloudflare Blog",
    url: "https://blog.cloudflare.com/rss",
    category: "ai_tech",
    region: "global",
    weight: 58,
  },
  {
    kind: "rss",
    name: "Product Hunt",
    url: "https://www.producthunt.com/feed",
    category: "ai_tech",
    region: "us",
    weight: 48,
  },
  {
    kind: "rss",
    name: "Stratechery",
    url: "https://stratechery.com/feed/",
    category: "finance",
    region: "us",
    weight: 64,
  },
  {
    kind: "rss",
    name: "Benedict Evans",
    url: "https://www.ben-evans.com/benedictevans?format=rss",
    category: "finance",
    region: "global",
    weight: 60,
  },
  {
    kind: "rss",
    name: "a16z Blog",
    url: "https://a16z.com/feed/",
    category: "finance",
    region: "us",
    weight: 58,
  },
  {
    kind: "rss",
    name: "VentureBeat",
    url: "https://feeds.feedburner.com/venturebeat/SZYF",
    category: "ai_tech",
    region: "us",
    weight: 56,
  },
  {
    kind: "rss",
    name: "BleepingComputer",
    url: "https://www.bleepingcomputer.com/feed/",
    category: "ai_tech",
    region: "us",
    weight: 60,
  },
  {
    kind: "rss",
    name: "KrebsOnSecurity",
    url: "https://krebsonsecurity.com/feed/",
    category: "ai_tech",
    region: "us",
    weight: 60,
  },
  {
    kind: "rss",
    name: "The Register",
    url: "https://www.theregister.com/headlines.atom",
    category: "ai_tech",
    region: "global",
    weight: 56,
  },
  {
    kind: "rss",
    name: "404 Media",
    url: "https://www.404media.co/rss/",
    category: "ai_tech",
    region: "us",
    weight: 54,
  },
  {
    kind: "rss",
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    category: "ai_tech",
    region: "us",
    weight: 66,
  },
  {
    kind: "rss",
    name: "MIT Technology Review",
    url: "https://www.technologyreview.com/feed/",
    category: "ai_tech",
    region: "us",
    weight: 64,
  },
  {
    kind: "rss",
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    category: "ai_tech",
    region: "us",
    weight: 63,
  },
  {
    kind: "rss",
    name: "论文预印本",
    url: "https://export.arxiv.org/rss/cs.AI",
    category: "ai_tech",
    region: "global",
    weight: 55,
  },
  {
    kind: "rss",
    name: "X · OpenAI",
    url: "https://nitter.net/OpenAI/rss",
    category: "ai_tech",
    region: "us",
    weight: 85,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Anthropic",
    url: "https://nitter.net/AnthropicAI/rss",
    category: "ai_tech",
    region: "us",
    weight: 85,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Google DeepMind",
    url: "https://nitter.net/GoogleDeepMind/rss",
    category: "ai_tech",
    region: "us",
    weight: 85,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Elon Musk",
    url: "https://nitter.net/elonmusk/rss",
    category: "ai_tech",
    region: "us",
    weight: 80,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Sam Altman",
    url: "https://nitter.net/sama/rss",
    category: "ai_tech",
    region: "us",
    weight: 82,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Andrej Karpathy",
    url: "https://nitter.net/karpathy/rss",
    category: "ai_tech",
    region: "us",
    weight: 80,
    enabled: false,
  },
];

export const MARKET_SYMBOLS = [
  { symbol: "000001.SS", name: "上证指数", category: "index_cn" },
  { symbol: "^HSI", name: "恒生指数", category: "index_global" },
  { symbol: "^IXIC", name: "纳斯达克", category: "index_global" },
  { symbol: "BTC-USD", name: "比特币", category: "crypto" },
  { symbol: "CNY=X", name: "美元/人民币", category: "fx" },
];
