import type { BriefingCategory } from "./types";

export interface PresetNewsSource {
  kind: "rss";
  name: string;
  url: string;
  category: BriefingCategory;
  region: "cn" | "global" | "us";
  weight: number;
  enabled?: boolean;
}

export const PRESET_NEWS_SOURCES: PresetNewsSource[] = [
  {
    kind: "rss",
    name: "英国广播公司中文网",
    url: "https://feeds.bbci.co.uk/zhongwen/simp/rss.xml",
    category: "world",
    region: "global",
    weight: 80,
  },
  {
    kind: "rss",
    name: "中国新闻网国际",
    url: "https://www.chinanews.com.cn/rss/world.xml",
    category: "world",
    region: "cn",
    weight: 76,
  },
  {
    kind: "rss",
    name: "中国新闻网财经",
    url: "https://www.chinanews.com.cn/rss/finance.xml",
    category: "finance",
    region: "cn",
    weight: 74,
  },
  {
    kind: "rss",
    name: "联合国新闻中文",
    url: "https://news.un.org/feed/subscribe/zh/news/all/rss.xml",
    category: "world",
    region: "global",
    weight: 78,
  },
  {
    kind: "rss",
    name: "联合国新闻全球",
    url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
    category: "world",
    region: "global",
    weight: 60,
  },
  {
    kind: "rss",
    name: "CBS 世界",
    url: "https://www.cbsnews.com/latest/rss/world",
    category: "world",
    region: "us",
    weight: 58,
  },
  {
    kind: "rss",
    name: "ABC 国际",
    url: "https://abcnews.go.com/abcnews/internationalheadlines",
    category: "world",
    region: "us",
    weight: 56,
  },
  {
    kind: "rss",
    name: "纽约时报中文网",
    url: "https://cn.nytimes.com/rss/",
    category: "world",
    region: "global",
    weight: 70,
  },
  {
    kind: "rss",
    name: "CNBC 全球市场",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    category: "finance",
    region: "us",
    weight: 66,
  },
  {
    kind: "rss",
    name: "CNBC 投资市场",
    url: "https://www.cnbc.com/id/15839069/device/rss/rss.html",
    category: "finance",
    region: "us",
    weight: 64,
  },
  {
    kind: "rss",
    name: "MarketWatch",
    url: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    category: "finance",
    region: "us",
    weight: 60,
  },
  {
    kind: "rss",
    name: "Seeking Alpha 快讯",
    url: "https://seekingalpha.com/market_currents.xml",
    category: "finance",
    region: "us",
    weight: 55,
  },
  {
    kind: "rss",
    name: "36氪",
    url: "https://36kr.com/feed",
    category: "ai_tech",
    region: "cn",
    weight: 65,
  },
  {
    kind: "rss",
    name: "极客公园",
    url: "https://www.geekpark.net/rss",
    category: "ai_tech",
    region: "cn",
    weight: 75,
  },
  {
    kind: "rss",
    name: "InfoQ 中文",
    url: "https://www.infoq.cn/feed",
    category: "ai_tech",
    region: "cn",
    weight: 72,
  },
  {
    kind: "rss",
    name: "少数派",
    url: "https://sspai.com/feed",
    category: "ai_tech",
    region: "cn",
    weight: 58,
  },
  {
    kind: "rss",
    name: "IT之家",
    url: "https://www.ithome.com/rss/",
    category: "ai_tech",
    region: "cn",
    weight: 74,
  },
  {
    kind: "rss",
    name: "爱范儿",
    url: "https://www.ifanr.com/feed",
    category: "ai_tech",
    region: "cn",
    weight: 70,
  },
  {
    kind: "rss",
    name: "钛媒体",
    url: "https://www.tmtpost.com/rss.xml",
    category: "ai_tech",
    region: "cn",
    weight: 68,
  },
  {
    kind: "rss",
    name: "量子位",
    url: "https://www.qbitai.com/feed",
    category: "ai_tech",
    region: "cn",
    weight: 68,
  },
  {
    kind: "rss",
    name: "Solidot",
    url: "https://www.solidot.org/index.rss",
    category: "ai_tech",
    region: "cn",
    weight: 60,
  },
  {
    kind: "rss",
    name: "海外科技媒体",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    category: "ai_tech",
    region: "us",
    weight: 70,
  },
  {
    kind: "rss",
    name: "海外科技媒体",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    category: "ai_tech",
    region: "us",
    weight: 70,
  },
  {
    kind: "rss",
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    category: "ai_tech",
    region: "us",
    weight: 66,
  },
  {
    kind: "rss",
    name: "MIT Technology Review",
    url: "https://www.technologyreview.com/feed/",
    category: "ai_tech",
    region: "us",
    weight: 64,
  },
  {
    kind: "rss",
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    category: "ai_tech",
    region: "us",
    weight: 63,
  },
  {
    kind: "rss",
    name: "论文预印本",
    url: "https://export.arxiv.org/rss/cs.AI",
    category: "ai_tech",
    region: "global",
    weight: 55,
  },
  {
    kind: "rss",
    name: "X · OpenAI",
    url: "https://nitter.net/OpenAI/rss",
    category: "ai_tech",
    region: "us",
    weight: 85,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Anthropic",
    url: "https://nitter.net/AnthropicAI/rss",
    category: "ai_tech",
    region: "us",
    weight: 85,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Google DeepMind",
    url: "https://nitter.net/GoogleDeepMind/rss",
    category: "ai_tech",
    region: "us",
    weight: 85,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Elon Musk",
    url: "https://nitter.net/elonmusk/rss",
    category: "ai_tech",
    region: "us",
    weight: 80,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Sam Altman",
    url: "https://nitter.net/sama/rss",
    category: "ai_tech",
    region: "us",
    weight: 82,
    enabled: false,
  },
  {
    kind: "rss",
    name: "X · Andrej Karpathy",
    url: "https://nitter.net/karpathy/rss",
    category: "ai_tech",
    region: "us",
    weight: 80,
    enabled: false,
  },
];

export const MARKET_SYMBOLS = [
  { symbol: "000001.SS", name: "上证指数", category: "index_cn" },
  { symbol: "^HSI", name: "恒生指数", category: "index_global" },
  { symbol: "^IXIC", name: "纳斯达克", category: "index_global" },
  { symbol: "BTC-USD", name: "比特币", category: "crypto" },
  { symbol: "CNY=X", name: "美元/人民币", category: "fx" },
];
